config/routes.rb
GrapeApi::Application.routes.draw do
  devise_for :users
  resources :steps

  resources :scenarios

  resources :features

  resources :projects

  

end

app/models/scenario.rb
class Scenario
  include Mongoid::Document
  field :scenario, type: String

  embedded_in :scenario
  embeds_many :steps
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  before_action :set_scenario, only: [:show, :edit, :update, :destroy]

  # GET /scenarios
  # GET /scenarios.json
  def index
    @scenarios = Scenario.all
  end

  # GET /scenarios/1
  # GET /scenarios/1.json
  def show
  end

  # GET /scenarios/new
  def new
    @scenario = Scenario.new
  end

  # GET /scenarios/1/edit
  def edit
  end

  # POST /scenarios
  # POST /scenarios.json
  def create
    @scenario = Scenario.new(scenario_params)

    respond_to do |format|
      if @scenario.save
        format.html { redirect_to @scenario, notice: 'Scenario was successfully created.' }
        format.json { render action: 'show', status: :created, location: @scenario }
      else
        format.html { render action: 'new' }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenarios/1
  # PATCH/PUT /scenarios/1.json
  def update
    respond_to do |format|
      if @scenario.update(scenario_params)
        format.html { redirect_to @scenario, notice: 'Scenario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenarios/1
  # DELETE /scenarios/1.json
  def destroy
    @scenario.destroy
    respond_to do |format|
      format.html { redirect_to scenarios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scenario
      @scenario = Scenario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scenario_params
      params.require(:scenario).permit(:scenario)
    end
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/views/scenarios/_form.html.erb
<%= form_for(@scenario) do |f| %>
  <% if @scenario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scenario.errors.count, "error") %> prohibited this scenario from being saved:</h2>

      <ul>
      <% @scenario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :scenario %><br>
    <%= f.text_field :scenario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scenarios/edit.html.erb
<h1>Editing scenario</h1>

<%= render 'form' %>

<%= link_to 'Show', @scenario %> |
<%= link_to 'Back', scenarios_path %>

app/views/scenarios/index.html.erb
<h1>Listing scenarios</h1>

<table>
  <thead>
    <tr>
      <th>Scenario</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scenarios.each do |scenario| %>
      <tr>
        <td><%= scenario.scenario %></td>
        <td><%= link_to 'Show', scenario %></td>
        <td><%= link_to 'Edit', edit_scenario_path(scenario) %></td>
        <td><%= link_to 'Destroy', scenario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scenario', new_scenario_path %>

app/views/scenarios/new.html.erb
<h1>New scenario</h1>

<%= render 'form' %>

<%= link_to 'Back', scenarios_path %>

app/views/scenarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Scenario:</strong>
  <%= @scenario.scenario %>
</p>

<%= link_to 'Edit', edit_scenario_path(@scenario) %> |
<%= link_to 'Back', scenarios_path %>